// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: encryption/v1/encryption.proto

package encryptionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RotateKeyPairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeyPairResponse) Reset() {
	*x = RotateKeyPairResponse{}
	mi := &file_encryption_v1_encryption_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeyPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeyPairResponse) ProtoMessage() {}

func (x *RotateKeyPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_v1_encryption_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeyPairResponse.ProtoReflect.Descriptor instead.
func (*RotateKeyPairResponse) Descriptor() ([]byte, []int) {
	return file_encryption_v1_encryption_proto_rawDescGZIP(), []int{0}
}

func (x *RotateKeyPairResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GenerateKeyPairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyPairResponse) Reset() {
	*x = GenerateKeyPairResponse{}
	mi := &file_encryption_v1_encryption_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyPairResponse) ProtoMessage() {}

func (x *GenerateKeyPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_v1_encryption_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyPairResponse.ProtoReflect.Descriptor instead.
func (*GenerateKeyPairResponse) Descriptor() ([]byte, []int) {
	return file_encryption_v1_encryption_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateKeyPairResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GenerateKeyPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	KeySize       int32                  `protobuf:"varint,2,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyPairRequest) Reset() {
	*x = GenerateKeyPairRequest{}
	mi := &file_encryption_v1_encryption_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyPairRequest) ProtoMessage() {}

func (x *GenerateKeyPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_v1_encryption_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyPairRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyPairRequest) Descriptor() ([]byte, []int) {
	return file_encryption_v1_encryption_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateKeyPairRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *GenerateKeyPairRequest) GetKeySize() int32 {
	if x != nil {
		return x.KeySize
	}
	return 0
}

type RotateKeyPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyRef        string                 `protobuf:"bytes,1,opt,name=key_ref,json=keyRef,proto3" json:"key_ref,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	KeySize       int32                  `protobuf:"varint,3,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeyPairRequest) Reset() {
	*x = RotateKeyPairRequest{}
	mi := &file_encryption_v1_encryption_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeyPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeyPairRequest) ProtoMessage() {}

func (x *RotateKeyPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_v1_encryption_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeyPairRequest.ProtoReflect.Descriptor instead.
func (*RotateKeyPairRequest) Descriptor() ([]byte, []int) {
	return file_encryption_v1_encryption_proto_rawDescGZIP(), []int{3}
}

func (x *RotateKeyPairRequest) GetKeyRef() string {
	if x != nil {
		return x.KeyRef
	}
	return ""
}

func (x *RotateKeyPairRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *RotateKeyPairRequest) GetKeySize() int32 {
	if x != nil {
		return x.KeySize
	}
	return 0
}

type EncryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyRef        string                 `protobuf:"bytes,1,opt,name=key_ref,json=keyRef,proto3" json:"key_ref,omitempty"`
	Plaintext     []byte                 `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptRequest) Reset() {
	*x = EncryptRequest{}
	mi := &file_encryption_v1_encryption_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequest) ProtoMessage() {}

func (x *EncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_v1_encryption_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequest.ProtoReflect.Descriptor instead.
func (*EncryptRequest) Descriptor() ([]byte, []int) {
	return file_encryption_v1_encryption_proto_rawDescGZIP(), []int{4}
}

func (x *EncryptRequest) GetKeyRef() string {
	if x != nil {
		return x.KeyRef
	}
	return ""
}

func (x *EncryptRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *EncryptRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type EncryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyRef        string                 `protobuf:"bytes,1,opt,name=key_ref,json=keyRef,proto3" json:"key_ref,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptResponse) Reset() {
	*x = EncryptResponse{}
	mi := &file_encryption_v1_encryption_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResponse) ProtoMessage() {}

func (x *EncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_v1_encryption_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResponse.ProtoReflect.Descriptor instead.
func (*EncryptResponse) Descriptor() ([]byte, []int) {
	return file_encryption_v1_encryption_proto_rawDescGZIP(), []int{5}
}

func (x *EncryptResponse) GetKeyRef() string {
	if x != nil {
		return x.KeyRef
	}
	return ""
}

func (x *EncryptResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EncryptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DecryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyRef        string                 `protobuf:"bytes,1,opt,name=key_ref,json=keyRef,proto3" json:"key_ref,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_encryption_v1_encryption_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_v1_encryption_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_encryption_v1_encryption_proto_rawDescGZIP(), []int{6}
}

func (x *DecryptRequest) GetKeyRef() string {
	if x != nil {
		return x.KeyRef
	}
	return ""
}

func (x *DecryptRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *DecryptRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type DecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyRef        string                 `protobuf:"bytes,1,opt,name=key_ref,json=keyRef,proto3" json:"key_ref,omitempty"`
	Plaintext     []byte                 `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	mi := &file_encryption_v1_encryption_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_v1_encryption_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_encryption_v1_encryption_proto_rawDescGZIP(), []int{7}
}

func (x *DecryptResponse) GetKeyRef() string {
	if x != nil {
		return x.KeyRef
	}
	return ""
}

func (x *DecryptResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *DecryptResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *DecryptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_encryption_v1_encryption_proto protoreflect.FileDescriptor

const file_encryption_v1_encryption_proto_rawDesc = "" +
	"\n" +
	"\x1eencryption/v1/encryption.proto\x12\rencryption.v1\"'\n" +
	"\x15RotateKeyPairResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x17GenerateKeyPairResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x16GenerateKeyPairRequest\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x19\n" +
	"\bkey_size\x18\x02 \x01(\x05R\akeySize\"h\n" +
	"\x14RotateKeyPairRequest\x12\x17\n" +
	"\akey_ref\x18\x01 \x01(\tR\x06keyRef\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x19\n" +
	"\bkey_size\x18\x03 \x01(\x05R\akeySize\"Y\n" +
	"\x0eEncryptRequest\x12\x17\n" +
	"\akey_ref\x18\x01 \x01(\tR\x06keyRef\x12\x1c\n" +
	"\tplaintext\x18\x02 \x01(\fR\tplaintext\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"r\n" +
	"\x0fEncryptResponse\x12\x17\n" +
	"\akey_ref\x18\x01 \x01(\tR\x06keyRef\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"[\n" +
	"\x0eDecryptRequest\x12\x17\n" +
	"\akey_ref\x18\x01 \x01(\tR\x06keyRef\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"p\n" +
	"\x0fDecryptResponse\x12\x17\n" +
	"\akey_ref\x18\x01 \x01(\tR\x06keyRef\x12\x1c\n" +
	"\tplaintext\x18\x02 \x01(\fR\tplaintext\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xf5\x02\n" +
	"\x11EncryptionService\x12N\n" +
	"\aEncrypt\x12\x1d.encryption.v1.EncryptRequest\x1a\x1e.encryption.v1.EncryptResponse\"\x00(\x010\x01\x12N\n" +
	"\aDecrypt\x12\x1d.encryption.v1.DecryptRequest\x1a\x1e.encryption.v1.DecryptResponse\"\x00(\x010\x01\x12b\n" +
	"\x0fGenerateKeyPair\x12%.encryption.v1.GenerateKeyPairRequest\x1a&.encryption.v1.GenerateKeyPairResponse\"\x00\x12\\\n" +
	"\rRotateKeyPair\x12#.encryption.v1.RotateKeyPairRequest\x1a$.encryption.v1.RotateKeyPairResponse\"\x00B\xb9\x01\n" +
	"\x11com.encryption.v1B\x0fEncryptionProtoP\x01Z>grpc-encryption-service/internal/pb/encryption/v1;encryptionv1\xa2\x02\x03EXX\xaa\x02\rEncryption.V1\xca\x02\rEncryption\\V1\xe2\x02\x19Encryption\\V1\\GPBMetadata\xea\x02\x0eEncryption::V1b\x06proto3"

var (
	file_encryption_v1_encryption_proto_rawDescOnce sync.Once
	file_encryption_v1_encryption_proto_rawDescData []byte
)

func file_encryption_v1_encryption_proto_rawDescGZIP() []byte {
	file_encryption_v1_encryption_proto_rawDescOnce.Do(func() {
		file_encryption_v1_encryption_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_encryption_v1_encryption_proto_rawDesc), len(file_encryption_v1_encryption_proto_rawDesc)))
	})
	return file_encryption_v1_encryption_proto_rawDescData
}

var file_encryption_v1_encryption_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_encryption_v1_encryption_proto_goTypes = []any{
	(*RotateKeyPairResponse)(nil),   // 0: encryption.v1.RotateKeyPairResponse
	(*GenerateKeyPairResponse)(nil), // 1: encryption.v1.GenerateKeyPairResponse
	(*GenerateKeyPairRequest)(nil),  // 2: encryption.v1.GenerateKeyPairRequest
	(*RotateKeyPairRequest)(nil),    // 3: encryption.v1.RotateKeyPairRequest
	(*EncryptRequest)(nil),          // 4: encryption.v1.EncryptRequest
	(*EncryptResponse)(nil),         // 5: encryption.v1.EncryptResponse
	(*DecryptRequest)(nil),          // 6: encryption.v1.DecryptRequest
	(*DecryptResponse)(nil),         // 7: encryption.v1.DecryptResponse
}
var file_encryption_v1_encryption_proto_depIdxs = []int32{
	4, // 0: encryption.v1.EncryptionService.Encrypt:input_type -> encryption.v1.EncryptRequest
	6, // 1: encryption.v1.EncryptionService.Decrypt:input_type -> encryption.v1.DecryptRequest
	2, // 2: encryption.v1.EncryptionService.GenerateKeyPair:input_type -> encryption.v1.GenerateKeyPairRequest
	3, // 3: encryption.v1.EncryptionService.RotateKeyPair:input_type -> encryption.v1.RotateKeyPairRequest
	5, // 4: encryption.v1.EncryptionService.Encrypt:output_type -> encryption.v1.EncryptResponse
	7, // 5: encryption.v1.EncryptionService.Decrypt:output_type -> encryption.v1.DecryptResponse
	1, // 6: encryption.v1.EncryptionService.GenerateKeyPair:output_type -> encryption.v1.GenerateKeyPairResponse
	0, // 7: encryption.v1.EncryptionService.RotateKeyPair:output_type -> encryption.v1.RotateKeyPairResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_encryption_v1_encryption_proto_init() }
func file_encryption_v1_encryption_proto_init() {
	if File_encryption_v1_encryption_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_encryption_v1_encryption_proto_rawDesc), len(file_encryption_v1_encryption_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encryption_v1_encryption_proto_goTypes,
		DependencyIndexes: file_encryption_v1_encryption_proto_depIdxs,
		MessageInfos:      file_encryption_v1_encryption_proto_msgTypes,
	}.Build()
	File_encryption_v1_encryption_proto = out.File
	file_encryption_v1_encryption_proto_goTypes = nil
	file_encryption_v1_encryption_proto_depIdxs = nil
}
